name: turn dylib to framework
on:
  workflow_dispatch:
  
jobs:
  my_job:
    name: aaa
    runs-on: macOS-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: run
      run: |
        pwd
        ls
        lipo -help
        lipo -create ./lib/arm64/libpdfium.dylib -output ./lib/arm64/pdfium
        lipo -create ./lib/x64/libpdfium.dylib -output ./lib/x64/pdfium
        xcodebuild -create-xcframework -framework ./lib/arm64/pdfium -framework ./lib/x64/pdfium -output ./pdfium.xcframework
        # lipo -create /Users/runner/work/pdfium_libs/pdfium_libs/ios/Frameworks/libpdfium.dylib -output pdfium
        # lipo -info ./pdfium
    - name: Publish framework
      uses: actions/upload-artifact@v3
      with:
        name: release-frameworks
        path: ./pdfium.xcframework
